apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
spec:
  type: NodePort
  selector:
    app: my-nginx   # MUST match deployment labels
  ports:
    - port: 80
      targetPort: 80
      # nodePort removed → auto-assigned
